### ISSUE TITLE
put to current branch

### ISSUE THREAD

**Issue by airtonix** [starkandwayne/git-multibranch-resource#5]
So while we can get from which ever branch changed, we can only push to one branch (since branch is required and is singular)?

Can the branch param in put point at a file that contains the branch name?

```yaml
resource_types:
- name: git-multibranch
  type: docker-image
  source: {repository: cfcommunity/git-multibranch-resource}

resources:
- name: repo
  type: git-multibranch
  source:
    uri: git@github.com:fusion-com-au/docker-alpine-node-git.git
    private_key: {{private_key}}
    branches: '.*'
    ignore_branches: '(master)'

jobs:
- name: "build"
  plan:
  - get: repo
    params: {depth: 1}
    trigger: true
  - task: build
    file: repo/do-things.sh
  - put: repo
    params:
      repository: repo
```
__full pipeline here: https://github.com/fusion-com-au/docker-alpine-node-git/blob/master/ci/pipeline.yml__

1. currently this throws an error on put, since `branch` is not defined in the resource `repo`.
2. If I set branch to master, then i can't update the branch that triggered the pipeline.
